In [1]:
import pandas as pd
import requests
from dotenv import load_dotenv
import os

In [2]:
load_dotenv()
api_key = os.getenv("x_cg_demo_api_key")

# url = "https://api.coingecko.com/api/v3/simple/price"
url = "https://api.coingecko.com/api/v3/coins/markets"
headers = {
    "x_cg_demo_api_key": api_key,
    "Content-Type": "application/json",
    "Accept": "application/json",
}
respuesta = requests.get(
    url=url,
    headers=headers,
    params={
        "vs_currency": "usd"
    }
)

In [3]:
print(respuesta.status_code)
print(respuesta.text)
data = respuesta.json()

200

In [4]:
print(data[0]["id"])

bitcoin

In [5]:
df=pd.DataFrame(data)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                100 non-null    str
 1   symbol                            100 non-null    str
 2   name                              100 non-null    str
 3   image                             100 non-null    str
 4   current_price                     100 non-null    float64
 5   market_cap                        100 non-null    int64
 6   market_cap_rank                   100 non-null    int64
 7   fully_diluted_valuation           100 non-null    int64
 8   total_volume                      100 non-null    float64
 9   high_24h                          100 non-null    float64
 10  low_24h                           100 non-null    float64
 11  price_change_24h                  100 non-null    float64
 12  price_change_percentage_24h       100 non-null    float64
 13  market_cap_change_24h             100 non-null    float64
 14  market_cap_change_percentage_24h  100 non-null    float64
 15  circulating_supply                100 non-null    float64
 16  total_supply                      100 non-null    float64
 17  max_supply                        54 non-null     float64
 18  ath                               100 non-null    float64
 19  ath_change_percentage             100 non-null    float64
 20  ath_date                          100 non-null    str
 21  atl                               100 non-null    float64
 22  atl_change_percentage             100 non-null    float64
 23  atl_date                          100 non-null    str
 24  roi                               9 non-null      object
 25  last_updated                      100 non-null    str
dtypes: float64(15), int64(3), object(1), str(7)
memory usage: 20.4+ KB

In [7]:
df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='str')

In [8]:
df[[
  "name",
  "symbol",
  "current_price"
    
]]

              name symbol  current_price
0          Bitcoin    btc   84319.000000
1         Ethereum    eth    2682.630000
2           Tether   usdt       0.999838
3              BNB    bnb     772.400000
4              XRP    xrp       1.500000
..             ...    ...            ...
95           Aptos    apt       0.771022
96        Ether.fi  ethfi       0.657295
97  Pudgy Penguins  pengu       0.009796
98           Flare    flr       0.007065
99          Beldex    bdx       0.075982

[100 rows x 3 columns]

In [9]:
df["precio_p"] =df[
    "current_price"
]/18

In [10]:
df[[
    
    "name",
    "symbol",
    "current_price",
    "precio_p"
]]

              name symbol  current_price     precio_p
0          Bitcoin    btc   84319.000000  4684.388889
1         Ethereum    eth    2682.630000   149.035000
2           Tether   usdt       0.999838     0.055547
3              BNB    bnb     772.400000    42.911111
4              XRP    xrp       1.500000     0.083333
..             ...    ...            ...          ...
95           Aptos    apt       0.771022     0.042835
96        Ether.fi  ethfi       0.657295     0.036516
97  Pudgy Penguins  pengu       0.009796     0.000544
98           Flare    flr       0.007065     0.000393
99          Beldex    bdx       0.075982     0.004221

[100 rows x 4 columns]

In [11]:
df.describe()

,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,market_cap_change_24h,market_cap_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,atl,atl_change_percentage,precio_p
count,100.000000,1.000000e+02,100.000000,1.000000e+02,1.000000e+02,100.000000,100.000000,100.000000,100.000000,1.000000e+02,100.000000,1.000000e+02,1.000000e+02,5.400000e+01,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,1000.755879,2.897049e+10,50.500000,3.125200e+10,2.027274e+09,1035.336618,992.528398,-25.113166,-3.374001,-7.537397e+08,-3.445518,1.910665e+13,1.912147e+13,2.636830e+13,1576.930385,-54.516427,3.140005e+01,1.724445e+05,5.559755e+01
std,8442.887173,1.729122e+11,29.011492,1.732487e+11,9.540098e+09,8735.814735,8376.459494,214.440969,4.655307,4.420956e+09,4.639773,1.143492e+14,1.143602e+14,1.466234e+14,12619.226841,35.776538,2.002404e+02,1.090072e+06,4.690493e+02
min,0.000002,5.980421e+08,1.000000,6.345200e+08,0.000000e+00,0.000002,0.000002,-2143.285069,-15.676760,-4.301222e+10,-15.371030,4.349036e+05,7.870777e+00,1.461249e+07,0.000004,-99.597500,5.636600e-11,0.000000e+00,9.555556e-08
25%,0.234680,1.025608e+09,25.750000,1.366366e+09,1.897146e+07,0.259887,0.229792,-0.095120,-6.542683,-1.802993e+08,-6.433340,4.120410e+08,5.166134e+08,4.610613e+08,1.017750,-85.582850,3.902745e-02,4.848275e+01,1.303779e-02
50%,1.000000,1.903160e+09,50.500000,2.643514e+09,1.171415e+08,1.000000,0.999740,-0.008496,-3.040070,-6.146252e+07,-3.330510,1.840797e+09,1.968527e+09,7.109658e+09,2.635000,-66.269910,3.989125e-01,3.558099e+02,5.555556e-02
75%,8.987500,4.669401e+09,75.250000,6.744466e+09,4.180903e+08,9.167500,8.725000,-0.000004,-0.007710,-1.242536e+07,-0.271468,1.077569e+10,1.557424e+10,4.092601e+10,46.845000,-19.249182,9.601425e-01,3.415423e+03,4.993056e-01
max,84319.000000,1.693843e+12,100.000000,1.693843e+12,8.133834e+10,87251.000000,83654.000000,3.330000,16.958390,4.112662e+08,16.895640,8.982327e+14,8.982327e+14,9.999900e+14,126080.000000,0.000000,1.447840e+03,1.015026e+07,4.684389e+03